version: '3'

services:
  workspace:
    build: .
    init: true
    environment:
      # used by kubectl
      - KUBECONFIG=/workspace/.devcontainer/kubeconfig.yaml
      # used by the Terraform provider hashicorp/helm
      - KUBE_CONFIG_PATH=/workspace/.devcontainer/kubeconfig.yaml
      - EARTHLY_BUILDKIT_HOST=tcp://earthly:8372
      - EARTHLY_REMOTE_CACHE=ghcr.io/beeinventor/terraform_kubernetes_postgres_operator_cache:master
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
    command: sleep infinity
    user: vscode

  # https://github.com/k3s-io/k3s/blob/release-1.21/docker-compose.yml
  k3s-server:
    hostname: k3s-server
    image: rancher/k3s:v1.21.14-k3s1
    command: server
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
      - K3S_TOKEN=terraform-kubernetes-postgres-operator
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=600
    volumes:
      # This is just so that we get the kubeconfig file out
      - .:/output
    ports:
      - 6443:6443 # Kubernetes API Server
      - 80:80 # Ingress controller port 80
      - 443:443 # Ingress controller port 443

  # https://docs.earthly.dev/ci-integration/remote-buildkit
  earthly:
    image: earthly/buildkitd:v0.6.14
    privileged: true
    environment:
      - BUILDKIT_TCP_TRANSPORT_ENABLED=true
    expose:
      - 8372
    volumes:
      # https://docs.earthly.dev/docs/guides/using-the-earthly-docker-images/buildkit-standalone#earthly_tmp_dir
      - earthly-tmp:/tmp/earthly:rw

volumes:
  earthly-tmp:
